[package]
name = "factura"
version = "0.1.0"
edition = "2024"
description = "A library to serialize raw json/toml data and convert it into PDF or HTML formatted invoices"
licence = "MIT"

[dependencies]
askama = "0.14.0"
genpdf = "0.2.0"
serde = "1.0.219"
toml = "0.9.2"
